name: multi_server_socket
version: 1.0.0
author: "Dart Team <misc@dartlang.org>"
homepage: http://github.com/dart-lang/multi_server_socket
description:
  A dart:io ServerSocket wrapper that listens on multiple ports.
dependencies:
  async: "^1.2.0"
dev_dependencies:
  test: "^0.12.0"
environment:
  sdk: ">=1.13.0 <2.0.0"
